title: Harold Castillo
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Data Specialist leading the creation and automation of key reports and dashboards for the contimous improvement initiative at Upfield. 
  <br><br>
  I'm a positive thinker, a problem solver and a professional in the BI/DA world with experience in multicultural settings, able to work in teams and independently. 
  <br><br>
  <a href="linkedin.com/in/harold-castillo">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/harold.castillo">View My Tableau Public Profile</a> 
  <br><br>
  <a href="www.notion.so/harold-castillo">View My Notion Profile</a>
  <br><br>
  <a href="https://haroldcastle.github.io/haroldcastle-portfolio/">View My Github Profile</a>  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
